"""
email_sender.py — send HTML summary email via Gmail SMTP.
Mirrors the n8n Build Summary Email + Send Summary Email nodes exactly.
"""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Dict

from config import GMAIL_SENDER, GMAIL_RECIPIENT, GMAIL_APP_PASSWORD

log = logging.getLogger(__name__)


def _build_html(summary: List[Dict]) -> str:
    table_rows = ""
    for i, item in enumerate(summary):
        bg       = "#f9f9f9" if i % 2 == 0 else "#ffffff"
        job_link = (
            f'<a href="{item["job_url"]}">View Job</a>'
            if item.get("job_url") else "-"
        )
        pdf_link = (
            f'<a href="{item["resume_url"]}">Download Resume</a>'
            if item.get("resume_url") else "-"
        )
        table_rows += f"""
        <tr style="background:{bg}">
          <td style="padding:8px;border:1px solid #ddd;text-align:center">{i+1}</td>
          <td style="padding:8px;border:1px solid #ddd">{item.get('company','')}</td>
          <td style="padding:8px;border:1px solid #ddd">{item.get('position','')}</td>
          <td style="padding:8px;border:1px solid #ddd;text-align:center">{job_link}</td>
          <td style="padding:8px;border:1px solid #ddd;text-align:center">{pdf_link}</td>
          <td style="padding:8px;border:1px solid #ddd;text-align:center">{item.get('status','')}</td>
        </tr>"""

    return f"""
<div style="font-family:Arial,sans-serif;max-width:900px">
  <h2 style="color:#2d6a9f">✅ ATS Resume Optimization Complete</h2>
  <p>{len(summary)} resume(s) processed and saved to your Google Drive.</p>
  <table style="border-collapse:collapse;width:100%;font-size:13px">
    <thead>
      <tr style="background:#2d6a9f;color:white">
        <th style="padding:10px;border:1px solid #ddd">#</th>
        <th style="padding:10px;border:1px solid #ddd">Company</th>
        <th style="padding:10px;border:1px solid #ddd">Position</th>
        <th style="padding:10px;border:1px solid #ddd">Job Posting</th>
        <th style="padding:10px;border:1px solid #ddd">Optimized Resume</th>
        <th style="padding:10px;border:1px solid #ddd">Status</th>
      </tr>
    </thead>
    <tbody>{table_rows}</tbody>
  </table>
  <br>
  <p style="font-size:12px;color:#666">Generated by ATS Resume Optimizer</p>
</div>"""


def send_summary_email(summary: List[Dict]) -> None:
    """
    Send HTML summary email via Gmail SMTP (App Password auth).
    """
    if not GMAIL_APP_PASSWORD:
        log.warning("GMAIL_APP_PASSWORD not set — skipping email")
        return

    count   = len(summary)
    subject = f"✅ {count} ATS Optimized Resume(s) Ready – Saved to Google Drive"
    html    = _build_html(summary)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = GMAIL_SENDER
    msg["To"]      = GMAIL_RECIPIENT
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.ehlo()
        server.starttls()
        server.login(GMAIL_SENDER, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_SENDER, GMAIL_RECIPIENT, msg.as_string())

    log.info("Summary email sent to %s", GMAIL_RECIPIENT)
